# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f01450f4a2dd11c871567264001bd55aaf98cfb8847b7744eedb8e4da8a03ec4722ee858f71cdd67433f73410b6a8409a24a399610541a89433c60f87501a815

test:
  secret_key_base: aadf7ede3c24ccc0266789c5011acaf4594f65b8f32e4ade81eec3ada5a448e28a731bd7555fae724ade78b2f44ef7aad0ea51051db655e6c53662dfcd8a6fb2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
